using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Representa un punto de escalada en la ruta
/// </summary>
[System.Serializable]
public class ClimbPoint
{
    public Vector3 position;
    public ClimbPointType type;
    public float difficulty; // 0-1, donde 1 es más difícil
    public List<ClimbPoint> connections = new List<ClimbPoint>();

    public ClimbPoint(Vector3 pos, ClimbPointType pointType, float diff = 0.5f)
    {
        position = pos;
        type = pointType;
        difficulty = diff;
    }
}

public enum ClimbPointType
{
    Handhold,      // Agarre de mano
    Foothold,      // Apoyo de pie
    HookPoint,     // Punto de gancho
    LedgeRest,     // Repisa para descansar
    Checkpoint     // Punto de control
}

/// <summary>
/// Sistema de pathfinding para encontrar rutas de escalada
/// </summary>
public class ClimbingPathfinder : MonoBehaviour
{
    [Header("Pathfinding Settings")]
    [SerializeField] private float maxClimbDistance = 2f;
    [SerializeField] private LayerMask climbableLayer;
    [SerializeField] private bool debugMode = false;

    private List<ClimbPoint> climbPoints = new List<ClimbPoint>();
    private Dictionary<ClimbPoint, float> gScore = new Dictionary<ClimbPoint, float>();
    private Dictionary<ClimbPoint, float> fScore = new Dictionary<ClimbPoint, float>();

    /// <summary>
    /// Inicializa los puntos de escalada desde la escena
    /// </summary>
    public void InitializeClimbPoints()
    {
        climbPoints.Clear();

        // Buscar todos los objetos escalables en la escena
        GameObject[] climbableObjects = GameObject.FindGameObjectsWithTag("escalable");
        
        foreach (GameObject obj in climbableObjects)
        {
            // Buscar componentes ClimbPointMarker
            ClimbPointMarker[] markers = obj.GetComponentsInChildren<ClimbPointMarker>();
            
            foreach (ClimbPointMarker marker in markers)
            {
                ClimbPoint point = new ClimbPoint(
                    marker.transform.position,
                    marker.pointType,
                    marker.difficulty
                );
                climbPoints.Add(point);
            }
        }

        // Conectar puntos cercanos
        ConnectClimbPoints();

        if (debugMode)
        {
            Debug.Log($"ClimbingPathfinder: Inicializados {climbPoints.Count} puntos de escalada");
        }
    }

    /// <summary>
    /// Genera puntos de escalada automáticamente en objetos escalables
    /// Útil para prototipado rápido o niveles procedurales
    /// </summary>
    [ContextMenu("Generate Climb Points Automatically")]
    public void GenerateClimbPointsAuto()
    {
        // Buscar todas las paredes con tag "escalable"
        GameObject[] walls = GameObject.FindGameObjectsWithTag("escalable");
        
        if (walls.Length == 0)
        {
            Debug.LogWarning("No se encontraron objetos con tag 'escalable'");
            return;
        }

        // Crear contenedor para los puntos generados
        GameObject container = GameObject.Find("AutoGeneratedClimbPoints");
        if (container == null)
        {
            container = new GameObject("AutoGeneratedClimbPoints");
        }

        int totalPointsGenerated = 0;

        foreach (GameObject wall in walls)
        {
            Renderer renderer = wall.GetComponent<Renderer>();
            if (renderer == null) continue;
            
            Bounds bounds = renderer.bounds;
            
            // Crear subcontenedor para esta pared
            GameObject wallContainer = new GameObject($"Points_{wall.name}");
            wallContainer.transform.SetParent(container.transform);

            // Generar grid de puntos
            for (float y = bounds.min.y; y < bounds.max.y; y += 2f)
            {
                for (float x = bounds.min.x; x < bounds.max.x; x += 1.5f)
                {
                    for (float z = bounds.min.z; z <= bounds.max.z; z += (bounds.size.z > 0.5f ? bounds.size.z : 0.5f))
                    {
                        Vector3 position = new Vector3(x, y, z);
                        
                        // Verificar que el punto esté cerca de la superficie
                        if (IsNearSurface(position, wall))
                        {
                            // Crear punto
                            GameObject point = new GameObject($"AutoPoint_{totalPointsGenerated}");
                            point.transform.position = position;
                            point.transform.SetParent(wallContainer.transform);
                            
                            ClimbPointMarker marker = point.AddComponent<ClimbPointMarker>();
                            
                            // Determinar tipo según altura
                            float heightRatio = (y - bounds.min.y) / bounds.size.y;
                            
                            if (heightRatio < 0.2f || heightRatio > 0.8f)
                            {
                                // Zonas de descanso en inicio y cerca del final
                                if (Random.value < 0.3f)
                                {
                                    marker.pointType = ClimbPointType.LedgeRest;
                                }
                                else
                                {
                                    marker.pointType = ClimbPointType.Handhold;
                                }
                            }
                            else if (Random.value < 0.15f)
                            {
                                // 15% de probabilidad de punto de gancho
                                marker.pointType = ClimbPointType.HookPoint;
                            }
                            else
                            {
                                marker.pointType = ClimbPointType.Handhold;
                            }
                            
                            // Dificultad aumenta con la altura
                            marker.difficulty = Mathf.Lerp(0.3f, 0.8f, heightRatio);
                            
                            totalPointsGenerated++;
                        }
                    }
                }
            }
        }

        Debug.Log($"ClimbingPathfinder: Generados {totalPointsGenerated} puntos automáticamente");
        
        // Inicializar los puntos recién creados
        InitializeClimbPoints();
    }

    /// <summary>
    /// Verifica si una posición está cerca de la superficie de un objeto
    /// </summary>
    private bool IsNearSurface(Vector3 position, GameObject obj)
    {
        Collider collider = obj.GetComponent<Collider>();
        if (collider == null) return false;

        // Verificar distancia al punto más cercano del collider
        Vector3 closestPoint = collider.ClosestPoint(position);
        float distance = Vector3.Distance(position, closestPoint);

        return distance < 0.5f; // Punto debe estar a menos de 0.5 unidades de la superficie
    }

    /// <summary>
    /// Limpia todos los puntos autogenerados
    /// </summary>
    [ContextMenu("Clear Auto-Generated Points")]
    public void ClearAutoGeneratedPoints()
    {
        GameObject container = GameObject.Find("AutoGeneratedClimbPoints");
        if (container != null)
        {
            if (Application.isPlaying)
            {
                Destroy(container);
            }
            else
            {
                DestroyImmediate(container);
            }
            
            Debug.Log("Puntos autogenerados eliminados");
            InitializeClimbPoints();
        }
        else
        {
            Debug.LogWarning("No hay puntos autogenerados para eliminar");
        }
    }

    /// <summary>
    /// Conecta automáticamente puntos de escalada cercanos
    /// </summary>
    private void ConnectClimbPoints()
    {
        for (int i = 0; i < climbPoints.Count; i++)
        {
            for (int j = i + 1; j < climbPoints.Count; j++)
            {
                float distance = Vector3.Distance(climbPoints[i].position, climbPoints[j].position);
                
                if (distance <= maxClimbDistance)
                {
                    // Verificar línea de visión
                    if (!Physics.Linecast(climbPoints[i].position, climbPoints[j].position, ~climbableLayer))
                    {
                        climbPoints[i].connections.Add(climbPoints[j]);
                        climbPoints[j].connections.Add(climbPoints[i]);
                    }
                }
            }
        }
    }

    /// <summary>
    /// Encuentra la mejor ruta usando A*
    /// </summary>
    public List<ClimbPoint> FindPath(Vector3 start, Vector3 goal, float difficultyModifier = 1f)
    {
        ClimbPoint startPoint = GetNearestClimbPoint(start);
        ClimbPoint goalPoint = GetNearestClimbPoint(goal);

        if (startPoint == null || goalPoint == null)
        {
            if (debugMode) Debug.LogWarning("No se encontraron puntos de inicio o destino");
            return null;
        }

        return AStar(startPoint, goalPoint, difficultyModifier);
    }

    /// <summary>
    /// Algoritmo A* para pathfinding
    /// </summary>
    private List<ClimbPoint> AStar(ClimbPoint start, ClimbPoint goal, float difficultyModifier)
    {
        HashSet<ClimbPoint> closedSet = new HashSet<ClimbPoint>();
        HashSet<ClimbPoint> openSet = new HashSet<ClimbPoint> { start };
        Dictionary<ClimbPoint, ClimbPoint> cameFrom = new Dictionary<ClimbPoint, ClimbPoint>();

        gScore.Clear();
        fScore.Clear();

        gScore[start] = 0;
        fScore[start] = HeuristicCostEstimate(start, goal);

        while (openSet.Count > 0)
        {
            ClimbPoint current = GetLowestFScore(openSet);

            if (current == goal)
            {
                return ReconstructPath(cameFrom, current);
            }

            openSet.Remove(current);
            closedSet.Add(current);

            foreach (ClimbPoint neighbor in current.connections)
            {
                if (closedSet.Contains(neighbor)) continue;

                float tentativeGScore = gScore[current] + DistanceCost(current, neighbor, difficultyModifier);

                if (!openSet.Contains(neighbor))
                {
                    openSet.Add(neighbor);
                }
                else if (tentativeGScore >= gScore.GetValueOrDefault(neighbor, float.MaxValue))
                {
                    continue;
                }

                cameFrom[neighbor] = current;
                gScore[neighbor] = tentativeGScore;
                fScore[neighbor] = gScore[neighbor] + HeuristicCostEstimate(neighbor, goal);
            }
        }

        if (debugMode) Debug.LogWarning("No se encontró camino válido");
        return null;
    }

    /// <summary>
    /// Calcula el costo heurístico (distancia al objetivo)
    /// </summary>
    private float HeuristicCostEstimate(ClimbPoint a, ClimbPoint b)
    {
        // Distancia euclidiana con penalización por altura
        float distance = Vector3.Distance(a.position, b.position);
        float heightDiff = Mathf.Abs(b.position.y - a.position.y);
        
        return distance + (heightDiff * 0.5f); // Penalizar subidas
    }

    /// <summary>
    /// Calcula el costo de movimiento entre dos puntos
    /// </summary>
    private float DistanceCost(ClimbPoint a, ClimbPoint b, float difficultyModifier)
    {
        float baseCost = Vector3.Distance(a.position, b.position);
        float difficultyCost = b.difficulty * difficultyModifier;
        
        return baseCost + difficultyCost;
    }

    /// <summary>
    /// Obtiene el punto con menor F score
    /// </summary>
    private ClimbPoint GetLowestFScore(HashSet<ClimbPoint> set)
    {
        ClimbPoint lowest = null;
        float lowestScore = float.MaxValue;

        foreach (ClimbPoint point in set)
        {
            float score = fScore.GetValueOrDefault(point, float.MaxValue);
            if (score < lowestScore)
            {
                lowestScore = score;
                lowest = point;
            }
        }

        return lowest;
    }

    /// <summary>
    /// Reconstruye el camino desde el objetivo hasta el inicio
    /// </summary>
    private List<ClimbPoint> ReconstructPath(Dictionary<ClimbPoint, ClimbPoint> cameFrom, ClimbPoint current)
    {
        List<ClimbPoint> path = new List<ClimbPoint> { current };

        while (cameFrom.ContainsKey(current))
        {
            current = cameFrom[current];
            path.Insert(0, current);
        }

        return path;
    }

    /// <summary>
    /// Encuentra el punto de escalada más cercano a una posición
    /// </summary>
    public ClimbPoint GetNearestClimbPoint(Vector3 position)
    {
        ClimbPoint nearest = null;
        float minDistance = float.MaxValue;

        foreach (ClimbPoint point in climbPoints)
        {
            float distance = Vector3.Distance(position, point.position);
            if (distance < minDistance)
            {
                minDistance = distance;
                nearest = point;
            }
        }

        return nearest;
    }

    /// <summary>
    /// Encuentra puntos de gancho cercanos
    /// </summary>
    public List<ClimbPoint> GetNearbyHookPoints(Vector3 position, float radius)
    {
        List<ClimbPoint> hookPoints = new List<ClimbPoint>();

        foreach (ClimbPoint point in climbPoints)
        {
            if (point.type == ClimbPointType.HookPoint)
            {
                if (Vector3.Distance(position, point.position) <= radius)
                {
                    hookPoints.Add(point);
                }
            }
        }

        return hookPoints;
    }

    /// <summary>
    /// Debug visual
    /// </summary>
    private void OnDrawGizmos()
    {
        if (!debugMode || climbPoints == null) return;

        // Dibujar puntos
        foreach (ClimbPoint point in climbPoints)
        {
            switch (point.type)
            {
                case ClimbPointType.Handhold:
                    Gizmos.color = Color.green;
                    break;
                case ClimbPointType.HookPoint:
                    Gizmos.color = Color.cyan;
                    break;
                case ClimbPointType.LedgeRest:
                    Gizmos.color = Color.yellow;
                    break;
                case ClimbPointType.Checkpoint:
                    Gizmos.color = Color.magenta;
                    break;
                default:
                    Gizmos.color = Color.white;
                    break;
            }

            Gizmos.DrawSphere(point.position, 0.2f);

            // Dibujar conexiones
            Gizmos.color = Color.gray;
            foreach (ClimbPoint connection in point.connections)
            {
                Gizmos.DrawLine(point.position, connection.position);
            }
        }
    }
}

/// <summary>
/// Componente para marcar puntos de escalada en la escena
/// </summary>
public class ClimbPointMarker : MonoBehaviour
{
    public ClimbPointType pointType = ClimbPointType.Handhold;
    [Range(0f, 1f)]
    public float difficulty = 0.5f;

    private void OnDrawGizmos()
    {
        Color color = Color.white;
        switch (pointType)
        {
            case ClimbPointType.Handhold: color = Color.green; break;
            case ClimbPointType.HookPoint: color = Color.cyan; break;
            case ClimbPointType.LedgeRest: color = Color.yellow; break;
            case ClimbPointType.Checkpoint: color = Color.magenta; break;
        }

        Gizmos.color = color;
        Gizmos.DrawWireSphere(transform.position, 0.3f);
    }
}
